version: "3"

services:
  don-beto-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge